{% set version = "4.5.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-rlab
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/Rlab_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/Rlab/Rlab_{{ version }}.tar.gz
  sha256: 8dbe8aec41f3b99904307c07c449850b34b9542d017353ac555a0836576ef2af

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('Rlab')"           # [not win]
    - "\"%R%\" -e \"library('Rlab')\""  # [win]

about:
  home: http://www.r-project.org, http://courses.ncsu.edu/ST370/distance/rlab
  license: GPL-2.0-or-later
  summary: Functions and Datasets Required for ST370 class
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: Rlab
# Title: Functions and Datasets Required for ST370 class
# Version: 2.15.1
# Date: Aug. 18, 2012
# Author: Dennis D. Boos, Douglas Nychka
# Maintainer: Dennis Boos <boos@stat.ncsu.edu>
# Depends: R (>= 2.10), utils
# Description: Functions and Datasets Required for ST370 class
# License: GPL (>= 2)
# URL: http://www.r-project.org, http://courses.ncsu.edu/ST370/distance/rlab
# Packaged: 2012-08-21 19:27:55 UTC; boos
# Repository: CRAN
# Date/Publication: 2012-08-22 05:44:15
# NeedsCompilation: no
