appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: HwYui6Zg8hA1wlHdp4ZGqpjYCIhEoCbP1ZWNKXSg5Ha5XwcVD/uwtxm6tRLfCz+lJOLUpzWSDwGMauRCvVNkOmnU8IE9b/8C/dcoKLt7+/pyl10Gft+EZHWHdG++ZK947pdhxiuITfwzvZoMYJMd4zcQzphSBsRcExk64T+Y9sJUMEx6ivUKknC205OzJ6k9/YSxYr0wLyfrZkecqYTdhjX5pr9H75AaHY3SHrDbXlW4qk6fODwA1cJcPCvIdRRwanVbneNzDwdbX0DCmPgfo510LwqEwR4NZ+pLTPFf3OlUMM1mkZ07I6NPurpvZ/3VRLG87Wi6w4KbalA+DIcUoW4q7ZyVdWytTSND2pOe8gXFkbKjRa8PA5OR5CsnPNs/nvEo11VA1rjYqKOv34MaskIaqqgftY/rlO17cIyxwxImpoInZ3BqjaeUO30azCJaknYaXglvMD1cGLhpwF1Wnb3XdTg8quLozODyGh17awSFPxtlDfJxAh26W0gJ87jrTuW+T8d4XAW0Aycqs4DvWWLMypLEvM1Up+gRyq0QkgS3hLHx11k/XZwzyTIH+HiVvIiVuOeK+xzjqwsz5XLOsPI10tXf+SOSbdNnbG6mKgZ0b8A/28ZmqbvrXxvHizUqby9qyNnfbWugPFes1DnjPsWn9JGABuBwkhLsXGYa9Qk=}
